# Copyright (c) 2026, Sowaan and contributors
# For license information, please see license.txt

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import flt, get_datetime, now_datetime, time_diff_in_hours

from transport.transport.utils import check_sales_order_exists, is_project_holiday

LMV_LABEL = "LMV (Light Motor Vehicle)"
HMV_LABEL = "HMV (Heavy Motor Vehicle)"


# Nothing has run yet at these statuses, so an actual start or end stamp on a
# Trip sitting at one of them cannot be a real observation.
PRE_START_STATUSES = ("Draft", "Assigned", "Accepted", "Rejected")


class Trip(Document):
	def validate(self):
		self.clear_unstarted_actuals()
		self.check_sales_order()
		self.set_route_endpoints()
		self.sync_stops_with_endpoints()
		self.check_double_booking()
		self.check_blacklisted_driver()
		self.set_duty_type()
		self.set_assigned()

	def clear_unstarted_actuals(self):
		"""Drop the driver's start/end stamps until the trip has actually begun.

		Frappe fills every blank Time field with the current wall-clock time
		when a document is built server-side (frappe/model/create_new.py -
		unlike Datetime, the Time branch is not gated on a "now" default), so a
		Trip generated by a Trip Schedule is born claiming it started and ended
		at the instant of generation. That is not a display nuisance: the fields
		are read as evidence the leg ran, by get_duration_hours(), by
		get_driver_hours_for_day() - which filters on `actual_start_time is
		set` - and by the timesheet pull, which copies them onto Transport
		Timesheet Trip and out into the driver-hours summary.
		"""
		if self.status in PRE_START_STATUSES:
			self.actual_start_time = None
			self.actual_end_time = None
			for stop in self.stops:
				stop.actual_time = None

	def sync_stops_with_endpoints(self):
		"""Stops are additive detail on top of from_place/to_place, which Route,
		the trip sheet and the timesheet matrix all still read. Keep the two
		representations from drifting: the first stop is the origin and the last
		is the destination."""
		if not self.stops:
			return

		if len(self.stops) < 2:
			frappe.throw(_("A Trip with stops needs at least two - an origin and a destination."))

		self.from_place = self.stops[0].place
		self.to_place = self.stops[-1].place

		if self.stops[0].scheduled_time:
			self.scheduled_time = self.stops[0].scheduled_time

	def check_sales_order(self):
		"""Only on creation, or if the Project is being changed - so switching
		this control on doesn't retroactively block edits to Trips that already
		exist on a site being brought into compliance."""
		if self.is_new() or self.has_value_changed("project"):
			check_sales_order_exists(self.project)

	def check_blacklisted_driver(self):
		if self.driver and frappe.db.get_value("Driver", self.driver, "is_blacklisted"):
			frappe.throw(_("Driver {0} is blacklisted and cannot be assigned to a Trip.").format(self.driver))

	def set_assigned(self):
		"""Driver & Vehicle Assignment (doc section 8) is a distinct step after
		Trip Planning (section 7): a Trip starts Draft and only becomes
		Assigned once both are set, which also starts the driver-confirmation
		escalation clock."""
		if self.status == "Draft" and self.vehicle and self.driver:
			self.status = "Assigned"
			self.assigned_on = now_datetime()
			self.reminder_sent = 0

	def set_route_endpoints(self):
		"""Fill from_place/to_place from the Route when creating a Trip by hand
		with only a Route selected. Does NOT touch scheduled_time here - by the
		time validate() runs, an unset Time field has already been silently
		filled with the current wall-clock time by Document.insert(), so a
		`self.scheduled_time or ...` fallback can never fire. Route selection
		on the client (trip.js) fills the standard time instead, while it's
		still genuinely blank in the browser."""
		if not self.route or (self.from_place and self.to_place):
			return

		route = frappe.get_doc("Route", self.route)
		if self.direction == "Drop":
			self.from_place, self.to_place = route.to_place, route.from_place
		else:
			self.from_place, self.to_place = route.from_place, route.to_place

	def check_double_booking(self):
		if not (self.trip_date and self.scheduled_time):
			return

		for fieldname, label in (("driver", _("Driver")), ("vehicle", _("Vehicle"))):
			value = self.get(fieldname)
			if not value:
				continue

			clash = frappe.db.exists(
				"Trip",
				{
					fieldname: value,
					"trip_date": self.trip_date,
					"scheduled_time": self.scheduled_time,
					"status": ("not in", ["Rejected", "Cancelled"]),
					"name": ("!=", self.name or ""),
				},
			)
			if clash:
				frappe.throw(
					_("{0} {1} is already booked on another Trip ({2}) at {3} on {4}.").format(
						label, value, clash, self.scheduled_time, self.trip_date
					)
				)

	def set_duty_type(self):
		if self.timesheet:
			# Already pulled onto a Transport Timesheet - what got billed must
			# not silently drift from what the Timesheet/OT report show, even
			# if a later same-day Trip is added and this one gets resaved.
			return

		if not self.trip_date:
			self.duty_type = "Duty"
			return

		if is_project_holiday(self.project, self.trip_date):
			# Weekend/PH duty is always OT, even the first trip of that day.
			self.duty_type = "OT"
			return

		if (frappe.db.get_single_value("Transport Settings", "ot_basis") or "Trips") == "Hours":
			self.set_duty_type_by_hours()
		else:
			self.set_duty_type_by_trip_count()

	def set_duty_type_by_hours(self):
		"""The client's driver-contract sheet defines overtime by hours worked
		("fixed full time 10 hours", OT after 10), not by trip count. Hours are
		per DRIVER per day - overtime is a payroll concept and the contract is
		the driver's, which is why this counts the driver's day rather than the
		vehicle's.

		A trip's hours are only knowable once it has actually run, so an
		unexecuted trip stays Duty and is re-evaluated when the driver ends it
		(see recalculate_duty_type, called from driver_portal.end_trip)."""
		duration = self.get_duration_hours()
		if not (self.driver and duration):
			self.duty_type = "Duty"
			return

		threshold = flt(frappe.db.get_single_value("Transport Settings", "daily_working_hours"))
		if not threshold:
			self.duty_type = "Duty"
			return

		hours_before_this = self.get_driver_hours_for_day()
		self.duty_type = "OT" if (hours_before_this + duration) > threshold else "Duty"

	def get_duration_hours(self):
		"""Worked hours for this leg, from the driver's own start/end stamps."""
		if not (self.actual_start_time and self.actual_end_time):
			return 0

		hours = time_diff_in_hours(self.actual_end_time, self.actual_start_time)
		# A leg running past midnight comes back negative; treat it as wrapping
		# to the next day rather than silently subtracting from the day's total.
		return hours + 24 if hours < 0 else hours

	def get_driver_hours_for_day(self):
		"""Hours this driver has already worked on this date, excluding this
		trip. Only counts legs that actually ran and were not rejected."""
		rows = frappe.get_all(
			"Trip",
			filters={
				"driver": self.driver,
				"trip_date": self.trip_date,
				"status": ("not in", ["Rejected", "Cancelled"]),
				"name": ("!=", self.name or ""),
				"actual_start_time": ("is", "set"),
				"actual_end_time": ("is", "set"),
			},
			fields=["actual_start_time", "actual_end_time"],
		)

		total = 0
		for row in rows:
			hours = time_diff_in_hours(row.actual_end_time, row.actual_start_time)
			total += hours + 24 if hours < 0 else hours
		return total

	def set_duty_type_by_trip_count(self):
		"""The workflow document's prose rule: LMV 5 / HMV 4 trips per day, any
		leg beyond that is OT. Kept alongside the hours rule because the two
		source documents disagree and the client has not confirmed which
		governs - switchable via Transport Settings.ot_basis."""
		if not (self.vehicle and self.vehicle_class):
			self.duty_type = "Duty"
			return

		daily_limit = self.get_daily_trip_limit()
		if not daily_limit:
			self.duty_type = "Duty"
			return

		trips_today = frappe.db.count(
			"Trip",
			{
				"vehicle": self.vehicle,
				"trip_date": self.trip_date,
				"status": ("not in", ["Rejected", "Cancelled"]),
				"name": ("!=", self.name or ""),
			},
		)
		self.duty_type = "OT" if trips_today >= daily_limit else "Duty"

	def get_daily_trip_limit(self):
		settings_field = "hmv_daily_trip_limit" if self.vehicle_class == HMV_LABEL else "lmv_daily_trip_limit"
		return frappe.db.get_single_value("Transport Settings", settings_field)


def recalculate_duty_type(trip_name):
	"""Re-evaluate Duty/OT once a trip's actual times exist. driver_portal's
	start/end use db_set (deliberately - a driver must never trigger a full
	save), which skips validate(), so hour-based OT would otherwise never be
	applied to the trip that just finished."""
	trip = frappe.get_doc("Trip", trip_name)
	if trip.timesheet:
		return trip.duty_type

	before = trip.duty_type
	trip.set_duty_type()
	if trip.duty_type != before:
		trip.db_set("duty_type", trip.duty_type)
	return trip.duty_type


@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def get_available_vehicles(doctype, txt, searchfield, start, page_len, filters=None):
	filters = frappe._dict(filters or {})
	trip_date, scheduled_time = filters.get("trip_date"), filters.get("scheduled_time")

	if not (trip_date and scheduled_time):
		frappe.throw(_("Set Trip Date and Scheduled Time first."))

	booked = frappe.get_all(
		"Trip",
		filters={
			"trip_date": trip_date,
			"scheduled_time": scheduled_time,
			"status": ("not in", ["Rejected", "Cancelled"]),
			"vehicle": ("is", "set"),
		},
		pluck="vehicle",
	)

	vehicle_filters = {"status": "Available", searchfield: ("like", f"%{txt}%")}
	if booked:
		vehicle_filters["name"] = ("not in", booked)
	if filters.get("vehicle_category"):
		vehicle_filters["vehicle_type"] = filters["vehicle_category"]

	return frappe.get_list(
		"Rental Vehicle",
		filters=vehicle_filters,
		fields=["name", "vehicle_make", "vehicle_model", "vehicle_class"],
		as_list=True,
		limit_start=start,
		limit_page_length=page_len,
	)


@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def get_available_drivers(doctype, txt, searchfield, start, page_len, filters=None):
	filters = frappe._dict(filters or {})
	trip_date, scheduled_time = filters.get("trip_date"), filters.get("scheduled_time")

	if not (trip_date and scheduled_time):
		frappe.throw(_("Set Trip Date and Scheduled Time first."))

	booked = frappe.get_all(
		"Trip",
		filters={
			"trip_date": trip_date,
			"scheduled_time": scheduled_time,
			"status": ("not in", ["Rejected", "Cancelled"]),
			"driver": ("is", "set"),
		},
		pluck="driver",
	)

	driver_filters = {"status": "Active", "is_blacklisted": 0, searchfield: ("like", f"%{txt}%")}
	if booked:
		driver_filters["name"] = ("not in", booked)

	return frappe.get_list(
		"Driver", filters=driver_filters, fields=["name", "full_name"],
		as_list=True, limit_start=start, limit_page_length=page_len,
	)
